server:
  port: ${PORT:8084}
  ssl:
    enabled: false
security:
  user:
    password: ${eureka.password}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_PASSWORD:password}
